[package]
name              = "common-base"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
binrw.workspace          = true
bytes.workspace          = true
parking_lot.workspace    = true
redis-protocol.workspace = true
serde.workspace          = true
